apiVersion: v1
kind: Service
metadata:
  name: {{ include "notional-agent-helm.fullname" . }}
  labels:
    app: notional-agent
    network: {{ .Values.agent.network }}
    {{- include "notional-agent-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.agent.app.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "notional-agent-helm.selectorLabels" . | nindent 4 }}
